
objs-y += cpu.o
objs-y += bios.o
objs-y += gb.o
objs-y += mmu.o
objs-y += rom.o
objs-y += io.o
objs-y += gpu.o
objs-y += debugger.o
objs-y += disasm.o
objs-y += timer.o

objs-y += mbc0.o
objs-y += mbc1.o
objs-y += mbc3.o
objs-y += mbc5.o

objs-y += cgb_colors.o
objs-y += cgb_themes.o

# subdir-y += gb_snd_emu
subdir-y += gb_apu

